### ISSUE TITLE
На этой линии не работает ввод, и нельзя ввести ссылку

### ISSUE THREAD

**Issue by Wolframko** [r4rdsn/vk-raid-defender#2]
На этой линии не работает ввод текста, и нельзя ввести ссылку, хотя в последующих этапах это возможно 
![image](https://user-images.githubusercontent.com/34187970/33555456-83b7b3ec-d911-11e7-8e22-f7f4983f30f9.png)

**Comment by r4rdsn** [comment]
вводимая ссылка, содержащая токен, намеренно не выводится в стандартный поток вывода, т. к. является конфиденциальной информацией. ссылку ввести возможно.

**Comment by r4rdsn** [comment]
вводимая ссылка, содержащая токен, намеренно не выводится в стандартный поток вывода, т. к. является конфиденциальной информацией. ссылку ввести возможно.
